name: todo_app
description: "A new Flutter project."
# Prevents accidental publishing to pub.dev
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Application versioning
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.6.2
  intl: ^0.20.1
  firebase_core: ^3.10.1
  firebase_auth: ^5.2.1
  flutter_slidable: ^3.1.2
  lottie: ^3.3.1
  flutter_bloc: ^8.1.3
  path_provider: ^2.1.2
  hydrated_bloc: ^9.1.3
  firebase_messaging: ^15.2.1
  fl_chart: ^0.63.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  image_picker: ^1.1.2
  firebase_storage: ^12.4.2
  appwrite: ^13.1.1
  connectivity_plus: ^6.1.2
  uuid: ^4.5.1


dev_dependencies:
  build_runner: ^2.4.7
  freezed: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  firebase_core_web: ^2.19.0
  json_serializable: ^6.9.3
  uuid: ^4.5.1

flutter:
  uses-material-design: true

  # Uncomment and update the following lines to include assets or custom fonts:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
