// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,





class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJqio6c1a-81AJ7ZlVfbuXFeCklQcSe1A',
    appId: '1:270567371286:web:3c184106d23bc8f2e9bb37',
    messagingSenderId: '270567371286',
    projectId: 'nurkhan',
    authDomain: 'nurkhan.firebaseapp.com',
    storageBucket: 'nurkhan.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB1cCB6J_ppT3jn9nZ4Vm-wnveFhJkKmM',
    appId: '1:270567371286:android:ae6e0994b261423ee9bb37',
    messagingSenderId: '270567371286',
    projectId: 'nurkhan',
    storageBucket: 'nurkhan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_W3Y_jVTuuU1YkcyNbk6xDR5Hy4l1DMA',
    appId: '1:270567371286:ios:d15314fd2c7f5092e9bb37',
    messagingSenderId: '270567371286',
    projectId: 'nurkhan',
    storageBucket: 'nurkhan.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );
}
